### ISSUE TITLE
Design Flaw in handling conversion errors?

### ISSUE THREAD

**Issue by thomass171** [perplexhub/rsql-jpa-specification#107]
I ran the following two queries on my test system
```
"type==A;from=lt=2020-12-02T11:30:00"
"type==A;from=lt=2020-12-02T10:30:00Z"
```
with the first returning 3 records and the second returning 0 records, even though the filters are effectively the same. The reason is that the conversion of '2020-12-02T10:30:00Z' to a LocalDateTime fails in RSQLVisitorBase:convert. That incident is only logged with level debug and operation continues with using 'null', which of course leads to a wrong result. 

Shouldn't such an incident cause an exception instead of silently ignoring it (from users viewpoint)?

**Comment by perplexhub** [comment]
@thomass171 could you review the fix?

**Comment by thomass171** [comment]
I'm afraid I don't get the idea of the 'fix'. You just change the log level. But do you expect a client system (user) to ask the admin to check the logs after performing a query?

**Comment by perplexhub** [comment]
The fix is to log the exception.
For your problem, I think you need to make some customizations for handling
date time if the standard way doesn’t work.

**Comment by mmichalko** [comment]
I agree with @thomass171  if the request has wrong format and it causes ConversionFailedException, we should not get it just silently logged and return wrong response, but the Exception should be thrown, so programmers can handle it by showing the client an error response, that his filter/sort parameters had wrong format.

Currently client does not know that his request was wrong, he just gets no results.

**Comment by nstdio** [comment]
I'm +1 on throwing exception. Silent behavior generates lots of confusion for clients.

**Comment by Phiwa** [comment]
I also agree with @thomass171 
The client has no chance to handle the problem and will unknowingly rely on incorrect data...

**Comment by mmichalko** [comment]
Wow, thank you very much for this change! Didnt expect it would be changed so fast. Already using the new version and it works nice.

I would suggest one more thing: since now the exception is thrown, it does not need to be also logged - because the catcher should be responsible for handling/logging - could this log be removed or changed the level, so that it is not visible by default? 
https://github.com/perplexhub/rsql-jpa-specification/blob/9a43235c6317728852b9f9c3a894ffa50b849e5d/rsql-common/src/main/java/io/github/perplexhub/rsql/RSQLVisitorBase.java#L89
