### ISSUE TITLE
Postgres ilike issue

### ISSUE THREAD

**Issue by maksutspahi** [perplexhub/rsql-jpa-specification#142]
Hello, on postgresql when using ilike query like 
`filter=name=ilike="query"`
it converts to this query:
`.... where lower(name) like '%query%' escape ''....`
but the problem with this query is that this do not work well with collated columns and just works well with english columns. (https://www.postgresql.org/docs/current/collation.html)

Suggestion:
 Postgres supports directly ilike operator. Can this be parsed to this sql which also respects collate of the column. Lowering the column is not even needed here.
`.... where name ilike '%query%' escape ''....`

I'm not sure if I'm missing something here is there a way to use 'ilike' operator for postgres instead of regular 'lower(query) like ....) I can understand that this is general jpa conversions and but is only way to create custom operator for this? Sorry if this question does not make sense.
Thank you

**Comment by ng-galien** [comment]
Hi, @maksutspahi,

IMO since ilike is not supported by [JPA](https://jakartaee.github.io/persistence/latest-nightly/api/jakarta.persistence/jakarta/persistence/criteria/CriteriaBuilder.html) we can't use it.
Regarding [last](https://en.wikipedia.org/wiki/List_of_SQL_reserved_words) SQL specification `ILIKE` keyword is only supported by Postgres. 

You can address your issue using a custom operator and call the postgres function equivalent to `ILIKE` as documented in README.

> Can be something as (not tested)

```sql
CREATE OR REPLACE FUNCTION like_ignore_case(text, text)
  RETURNS boolean AS
$BODY$
    SELECT $1 ILIKE $2;
$BODY$
LANGUAGE sql IMMUTABLE STRICT;
```

```java
RSQLCustomPredicate<String> customPredicate = new RSQLCustomPredicate<>(new ComparisonOperator("=likeIgnoreCase="), String.class,
      input -> {
	      var criteriaBuilder = input.getCriteriaBuilder();
	      var mappingProcedure = "like_ignore_case";
	      var column = input.getPath().as(String.class);
	      var comparison = input.getArguments().get(0);
	      var function = criteriaBuilder.function(mappingProcedure, Boolean.class, column, criteriaBuilder.literal(comparison));
	      return criteriaBuilder.isTrue(function);
      }
);
```
